export { Header } from "./Header/Header";
export { Body } from "./Body/Body";
export { TabBarComponent } from "./TabBar/TabBar";
export { World } from "./World/Word";
export { Why } from "./Why/Why";
export { Boost } from "./Boost/Boost";
export { Learn } from "./Learn/Learn";
export { Schools } from "./Schools/ Schools";
export { English } from "./English/English";
export { Effective } from "./Effective/Effective";
export { Footer } from "./Footer/Footer";
